var message = "Hello World";
console.log(message);
var number = 99;
console.log(number);
var boolean = true;
console.log(boolean);
var array = ["jo", "john", "jib"];
console.log(array);
var array2 = [1, 2, 3];
console.log(array2);
var array3 = [true, false, true];
console.log(array3);
var object = { name: "jo", age: 18, address: { provine: "bangkok", zipcode: 10120 }, isAdmin: false, data: ["id", "image"] };
console.log(object);
